### ISSUE TITLE
[ASAP] monitors / MPS for scaled out new model elements

### ISSUE THREAD

**Issue by kjuli** [PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-Monitoring#14]
julijan says there should be some code, somewhere. 

figure out where taht code is and whether it still works. and what it already covers.

**Comment by kjuli** [comment]
The code doesn't exist, i.e. even if new monitor elements are created, they are not really interpreted. Thus the goal is that
1. Also create new monitors and MPS when scaling out (through QVTo or programmatically?)
2. Interprete these new monitors in the monitor simulator

**Comment by klinakuf** [comment]
Target: week 39.

**Comment by kjuli** [comment]
There is now an implementation for creating new monitors for new resource containers. The problem is now that some simulators require a valid URI of the new resource containers, but since they are not saved into the file / resource set, the measuring points don't work:

The following is an exception when the Usage-Monitor tries to register the new measuring point (or rather, when it wants to check whether the measuring point is meant for it):

```
java.lang.IllegalArgumentException: Could not get eObject with URI platform:/resource/RemoteMeasuringMosaic/rm.resourceenvironment#_FNCi0HabEe61W5TsA_qNmg
	at org.palladiosimulator.commons.emfutils.EMFLoadHelper.loadAndResolveEObject(EMFLoadHelper.java:57)
	at org.palladiosimulator.commons.emfutils.EMFLoadHelper.loadAndResolveEObject(EMFLoadHelper.java:40)
	at org.palladiosimulator.commons.emfutils.EMFLoadHelper.loadAndResolveEObject(EMFLoadHelper.java:36)
	at org.palladiosimulator.analyzer.slingshot.behavior.usagesimulation.monitor.UsageScenarioResponseTimeMonitoringBehavior.onMeasurementSpecificationVisited(UsageScenarioResponseTimeMonitoringBehavior.java:64)
```

**Comment by stiesssh** [comment]
TODO: check whether this is already fixed, if so, close issue.

**Comment by klinakuf** [comment]
Feature is there
